name: Deploy with Chromatic

on: push

jobs:
chromatic-deployment:
runs-on: ubuntu-latest

steps:

uses: actions/checkout@v2

- name: Install dependencies
run: yarn
- name: Publish to Chromatic
uses: chromaui/action@v1
with:
token: ${{ secrets.CHROM_GITHUB_TOKEN }}
projectToken: ${{ secrets.MY_SECRET_TOKEN }}
