

name: Deploy Chromatic

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
      with:
       fetch-depth: 0 
    - name: Install dependencies
      run: yarn
    - name: Publish chromatic
      uses: chromaui/action@v1
      with:
        server: ftp.eleclere.devwebgarneau.com
        token: ${{ secrets.CHROM_GITHUB_TOKEN }}
        projectToken: ${{ secrets.MY_SECRET_TOKEN }}   

